# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./
    binary: kml2gpx
    ldflags:
      - "-X main.version={{ incpatch .Version }} -s -w"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: kml2gpx
    repository:
      branch: "homebrew-kml2gpx"
      name: homebrew-tap
      owner: yardbirdsax
      pull_request:
        enabled: true
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      