# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./
    binary: kml2gpx
    ldflags:
      - "-X main.version={{ incpatch .Version }} -s -w"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: 'checksums.txt'
release:
  mode: replace
snapshot:
  name_template: "{{ incpatch .Version }}-next"
# TODO: Enable this
# brews:
#   - name: kml2gpx
#     repository:
#       branch: "homebrew-kml2gpx"
#       name: homebrew-tap
#       owner: yardbirdsax
#       pull_request:
#         enabled: true
#       token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      